[[commands]]
id = "weather"
type = "lua"
script = "script.lua"
timeout = 5000
sandbox = "standard"

[commands.phrases]
ru = ["какая погода в {city}", "погода {city}"]
en = ["what's the weather in {city}", "weather in {city}"]

[commands.sounds]
ru = ["weather_ru_1", "weather_ru_2"]
en = ["weather_en_1", "weather_en_2"]

[commands.slots.city]
entity = "city name"
context = ["in", "for", "at", "в", "для"]


[[commands]]
id = "set_city"
type = "lua"
script = "set_city.lua"
sandbox = "standard"
timeout = 5000
phrases = [
    "установи город",
    "set city",
    "change city",
]