[voice]
id = "jarvis-remaster"
name = "Jarvis New"
author = "Abraham (Priler)"
languages = ["ru", "ua", "en"]

[reactions.ru]
# app startup
greet = ["greet1"]
greet_morning = ["greet_morning"]
greet_day = ["greet_day"]
greet_evening = ["greet_evening"]
greet_night = ["greet_night"]

# wake word detected
reply = ["reply1", "reply2", "reply3", "reply4", "reply5", "reply6"]

# command executed
ok = ["ok1", "ok2", "ok3", "ok4"]

# command not found
not_found = []

# thanks
thanks = ["thanks"]

# error
error = []

# goodbye
goodbye = []



[reactions.ua]
# app startup
greet = []
greet_morning = ["greet_morning1", "greet_morning2", "greet_morning3"]
greet_day = ["greet_day1", "greet_day2"]
greet_evening = ["greet_evening1", "greet_evening2"]
greet_night = ["greet_night1", "greet_night2"]

# wake word detected
reply = ["reply1", "reply2", "reply3", "reply4", "reply5"]

# command executed
ok = ["ok1", "ok2", "ok3", "ok4", "ok5", "ok6"]

# command not found
not_found = []

# thanks
thanks = []

# error
error = []

# goodbye
goodbye = []



[reactions.en]
# app startup
greet = []
greet_morning = ["greet_morning"]
greet_day = ["greet_day"]
greet_evening = ["greet_evening"]
greet_night = ["greet_night"]

# wake word detected
reply = ["reply1", "reply2", "reply3", "reply4", "reply5"]

# command executed
ok = ["ok1", "ok2", "ok3", "ok4", "ok5", "ok6"]

# command not found
not_found = []

# thanks
thanks = []

# error
error = []

# goodbye
goodbye = []