[voice]
id = "jarvis-og"
name = "Jarvis OG"
author = "Abraham (Priler)"
languages = ["ru"]

[reactions.ru]
# app startup
greet = ["run"]

# wake word detected
reply = ["reply1", "reply2", "reply3"]

# command executed
ok = ["ok1", "ok2", "ok3", "ok4"]

# command not found
not_found = ["not_found"]

# thanks
thanks = ["thanks"]

# error
error = []

# goodbye
goodbye = ["off"]